### ISSUE TITLE
svg graphs broken in v1.8.3

### ISSUE THREAD

**Issue by pavarnos** [phpmetrics/PhpMetrics#189]
installed latest version.
ran phpmetrics from the command line
overcame memory limit problem from #188 by doubling memory to 1024M.
Chrome reports javascript errors. Ditto in Firefox and Safari
<img width="851" alt="phpmetrics_report_-_by_jean-francois_lepine" src="https://cloud.githubusercontent.com/assets/589595/13476293/045d0748-e12c-11e5-8284-4dd23d1d4323.png">

line 1618 begins
```javascript
d3=function(){function n(n)
```

**Comment by theofidry** [comment]
Same issue, besides it's worth noting that `phpmetrics -V` returns `1.0.0` regardless of your version...

**Comment by theofidry** [comment]
Actually I tried to use an older version (1.7) and still see this issue...

**Comment by GWillmann** [comment]
Temporary workaround for me was to add `<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>` in the generated html file header...

**Comment by theofidry** [comment]
Thanks for the workaround @GWillmann, without it phpmetrics is unusable as I can't even explore the stats anymore.

**Comment by mrVictorios** [comment]
Hello,

i have the same issue when i use the composer versions. when i use phar is all fine
![bildschirmfoto 2016-03-07 um 20 36 20](https://cloud.githubusercontent.com/assets/7589465/13580864/63cdc458-e4a4-11e5-8590-e75a412b455c.png)

**Comment by UFOMelkor** [comment]
I cannot reproduce the error on my local machine :-/ (linux, php 7, phpmetrics 1.8.3 / master, opera/firefox). Perhaps you may provide some information about your setup?

When looking at the screenshot of @mrVictorios it seems that something replaced the `<<` after `(s&&c)` with a `\`.

@theofidry Wrong version output has been fixed in 0d95352. It will be available with the next release.

**Comment by mrVictorios** [comment]
Setup:
osx, php 5.6, phpmetrics / master

Ive compare the report from phar and composer version,
![bildschirmfoto 2016-03-08 um 23 59 37](https://cloud.githubusercontent.com/assets/7589465/13619539/def0a5c0-e589-11e5-9fba-703fde405a2e.png)
![bildschirmfoto 2016-03-08 um 23 59 19](https://cloud.githubusercontent.com/assets/7589465/13619540/df1f8796-e589-11e5-931a-27c5b2896236.png)

Left output from phar 1.8.3 and right output from composer,

I pulled the master to replace the js in the d3js.js.twig but result will be the same.

I'am continue searching the next days.

**Comment by theofidry** [comment]
@UFOMelkor I'm using PHP 5.6 on OSX 10.9.

**Comment by GWillmann** [comment]
@UFOMelkor I'm using PHP 5.5.31 on OSX 10.11.3 with Firefox 44.0.2 and phpmetrics 1.8.3 / master

**Comment by halfer** [comment]
Same here, 1.8.3 on Ubuntu 14.04 with PHP 5.5.9 and FF45. I've downgraded to 1.3 and still get the same now, no idea what is going wrong - was fairly sure it worked on an earlier version. I wonder if the generation process fails silently and outputs a corrupted report?

I use this config.yml file:

```
# Configuration for PHPMetrics
myconfig:
    # Can I add the 'lib' reference here somewhere?
    path:
        extensions: php
        # Can this be split into pieces?
        exclude: lib/WebScraper/Model/om|lib/WebScraper/Model/map|lib/JobScraper/Model/om|lib/JobScraper/Model/map|lib/JobScraper/ModelFrontEnd/om|lib/JobScraper/ModelFrontEnd/map|lib/OSGB36|vendor|app/templates|app/web

    # report and violations files
    logging:
        report:
            html: ./app/web/report.html

```

If my doing some debugging would help, please ping me with what class to look at.
