### ISSUE TITLE
All to specify several directories

### ISSUE THREAD

**Issue by theofidry** [phpmetrics/PhpMetrics#212]
As of now, we can specify the directory path in the config file:

``` yaml
default:
    path:
        directory: src
```

But what about being able to specify several directories? For example we could have:

``` yaml
default:
    path:
        directory:
            - legacy
            - src    
```
